### ISSUE TITLE
Plot fit against data

### ISSUE THREAD

**Issue by sebapersson** [sebapersson/PEtab.jl#100]
Currently we do not support plotting of the model fit against the data for each observable and simulation condition. This should definitely be added, and could make a first good issue.

Technically, simulated values can already be obtained via `petab_problem.compute_simulated_values(p0)` where they appear in the same order as in the measurement data. What would be left would be to correctly map simulation condition and observable for each condition when making the plot.

**Comment by TorkelE** [comment]
Would something like
`plot(res::Union{PEtabOptimisationResults,PEtabMultistartOptimisationResults}, model::PEtabModel; condition::String=get_default_condition(model), kwargs...)`
be a good interface?

(also, should there maybe be a constant or supertype declared for `Union{PEtabOptimisationResults,PEtabMultistartOptimisationResults}`?)

**Comment by TorkelE** [comment]
Good point, missed observables. An alternative is to have observables be a vector with the Symbols of the observables that you want to plot, e.g.
```julia
..., observable = [:A, :B])
```
By default, all observables are chosen. If you want less (presumably one, a subset is chosen.
(Only time I had multiple observables this worked mostly fine, but I admit there is a problem when they are on widely different sales)

Unless we cannot find a good alternative, I think the `plot(...)` overload should return a single plot (which is plotted). If we cannot find a good default we maybe could create an alternative function, e.g. `get_obs_comparisson_plots` that returns the different plots (for the user to specify).

One alternative is that (if there are more than 1 observables) we force the user to specify which one(s) they have in the plot (rather than getting a default choice with all).

**Comment by sebapersson** [comment]
I agree that plot should only return a single observable (as it makes most sense).

I think maybe we can by default plot all observables for a condition, and if we notice drastic difference in scale we can throw a warning recommending the user to plot them separately?

I also think we should add a function like `get_obs_comparisson_plots` to produce one plot for each observable for each condition, as these kind of plots are popular to but in the supplementary of a paper.

**Comment by TorkelE** [comment]
> I think maybe we can by default plot all observables for a condition, and if we notice drastic difference in scale we can throw a warning recommending the user to plot them separately?

> I also think we should add a function like get_obs_comparisson_plots to produce one plot for each observable for each condition, as these kind of plots are popular to but in the supplementary of a paper.


Both these sounds good.

**Comment by sebapersson** [comment]
Great do you have time to look at it, otherwise I can fix it (after I am done planning the teaching which starts soon)

**Comment by TorkelE** [comment]
Away this week, and some catch up to do after that, but could probably do it next, shouldn't be that complicated

**Comment by sebapersson** [comment]
As for help with this, in the PEtabODEProblem there is a function named `petab_problem.compute_simulated_values(x0)` (which is lacking from the docs which I should fix), which for a parameter vector x0 computes the simulated values (with correct observable values, transformation etc...) following the order that can be found in the internal `MeasurementsInfo` struct, which also stores simulation conditions ids. 

So maybe the best solution would be to just use `petab_problem.compute_simulated_values(x0)`, and then to get the observable data just use the data in `MeasurementsInfo`, this would also require to put `MeasurementsInfo` into the `PEtabODEProblem` struct (it is not a part of it currently, but should)

**Comment by TorkelE** [comment]
Sounds good, I already have a working version without (that I think is quite straightforward). Will push soon and then you can check if you'd rather modify the implementation though.

**Comment by sebapersson** [comment]
Closed by #149
