### ISSUE TITLE
`verbose=false` for `PEtabODEProblem(petab_model)`

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#124]
Looked in the docs, but could not find a verbose argument for this (although I found for other stuff). E.g. in documentation it would be nice to turn fo for e.g.:
![image](https://github.com/sebapersson/PEtab.jl/assets/18099310/a4b7438a-2ab9-4363-a660-cc33ed158f8e)

**Comment by sebapersson** [comment]
Thanks for pointing this out, there is a verbose argument (actually a large list of arguments) but they do not appear in the API documentation I now see. I think this happens because the struct definitions appears in a different location from the struct constructor, I will take a look to see if I can get the constructor into the documentation.

**Comment by sebapersson** [comment]
Closed by #126
