### ISSUE TITLE
Dealing with `Measurement noise σ is smaller than 0. Consider changing the noise formula so it cannot go below zero`

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#154]
I am trying to fit parameters to a model where I have `PEtabObservables` of the form
```julia
PEtabObservable(S, S*0.05)
```
where `S` is a species. When calling `calibrate_model_multistart` I get:
```
┌ Warning: Measurement noise σ is smaller than 0. Consider changing the noise formula so it
│ cannot go below zero. This issue likelly happens due to numerical noise when solving the ODE
└ @ PEtab ~/.julia/packages/PEtab/fBBay/src/Compute_cost/Compute_cost.jl:242
```

Some of the species that are measured may be very small, so I guess it is possible that, due to numeric error, `S<0.0`, and thus the noise formula.

I just wanted to check what the recommended way of dealing with this is. Most natural seems to be using
```julia
PEtabObservable(S, max(S*0.05, 0.0))
```
However, I wanted to double check whether this is indeed the recommended way.

**Comment by sebapersson** [comment]
It is due to numerical noise you get this problem, as when you do parameter estimation some of the initial guess parameter can be so bad that despite low tolerances the solutions goes below zero when the algorithms tries to find the optima.

How to deal with it? 
* I would not use the `max` function as this makes the function discontinuous and I can imagine it to be bad for gradient computations. 
* An alternative is to just live with it (and this warning has `maxlog=10` so it is manageable). When doing multistart parameter estimation none of your start-guesses are going to have this issue (as the start-guess function does not choose parameters that return `Inf`), so this problem likely arises during the line-search, as sometimes during line-search very bad parameter values can be suggested (e.g. for many models at times we fail to solve the ODE).  Usually the step-search algorithms just shrinks the step-length to handle this, and if you have more than 100 start-guesses it is okay that some of them have problems. Do you see any problems with parameter estimation convergence?
* Use a more robust noise-formula. Instead of a proportional noise formula sometimes a combined can make more sense https://monolix.lixoft.com/statistical-model/errormodel/ (but which noise formula to use naturally depends on how the data was gathered).

**Comment by TorkelE** [comment]
sounds good

yes, just ignoring it might be best for now
