### ISSUE TITLE
What (if anything) should I do about ` Warning: The supplied DiffCache was too small and was enlarged.`?

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#158]
When I run a (multistart) optimisation (with 2 runs and the `IPNewton()` method) problem I get 10 or so messages like:
``
┌ Warning: The supplied DiffCache was too small and was enlarged. This incurs allocations
│     on the first call to `get_tmp`. If few calls to `get_tmp` occur and optimal performance is essential,
│     consider changing 'N'/chunk size of this DiffCache to 99.
└ @ PreallocationTools ~/.julia/packages/PreallocationTools/ZXCTh/src/PreallocationTools.jl:191
```

How "worried" should I be about this? Is this just some minor slowdown, or something which I should try to deal with?

**Comment by sebapersson** [comment]
This only happens the first time the Hessian function is run, and it is due to me counting badly (we use PreallocationTools.jl). As the Hessian is called > 1000 of times, this will hardly at all affect performance.

So it will not affect performance at all, but it is irritating. We should keep this issue open until I have patched this.

Thanks for noticing.
