### ISSUE TITLE
Recommended way to handle uncertainty in initial conditions

### ISSUE THREAD

**Issue by TorkelE** [sebapersson/PEtab.jl#159]
I have a case from chemistry where data have been collected on a system over time. The experiments work by the chemist first putting some amounts of species into a container, and then (over time) measuring the concentration of some species.

There are two types of noise:
- Measurement noise, which can be handled (relatively) straightforwardly.
- Initial condition noise. I.e. the experimentalist might have recorded that they added 2µM of compound `A` to the initial mix. In reality, it might have been more like 2.05µM. In practice, I would assume that the initial condition is some normal distribution around the given value (which ideally I'd like to define similarly as for the observables).

Currently, my best idea for an approach is to:
Make initial conditions parameters: https://docs.sciml.ai/Catalyst/stable/catalyst_functionality/dsl_description/#Setting-initial-conditions-that-depend-on-parameters. Next, make these parameters that are estimated as part of the parameter fitting process. To these, ad a prior corresponding to by belief given what the experimentalist said about the experimental condition.

In practise, to figure out the parameters, the experimentalist performs several experiments, each with different initial conditions. Here, I would have to make the initial condition parameters condition-specific and estimate for each experiment. Here, if I have 5 initial conditions and 10 experiments, I add 50 parameters (to the maybe around 10 I am actually trying to figure out).

I feel this should work, but that there might be some neater way to handle this? I figured I should ask for advice in case you had any ideas.

**Comment by sebapersson** [comment]
This is an interesting case. And I think your approach is correct. 

So I would consider the initial values to be condition-specific parameters, that you can put good priors on, see here https://sebapersson.github.io/PEtab.jl/stable/Julia_condition_specific/. As you do not know the value of the initial parameters they should be treated as something you estimate (so you do not get a bias from fixating the values).

Now, this is a regime where you might get bad performance due to having many condition specific parameters. When building the `petab_problem` I would recommend the following settings:

```julia
petab_problem = PEtabODEProblem(petab_model; gradient_method=:ForwardDiff, hessian_method=:ForwardDiff, split_over_conditions=true)
```

Here `split_over_conditions=true` ensures that for each experimental condition a call to ForwardDiff.jl is made, instead of a single call for all conditions. As you have many parameters that only appear for certain conditions the cost of restarting ForwardDiff is going to be smaller than the cost of having to propagate duals through an experimental condition where a parameter does not appear.

**Comment by TorkelE** [comment]
Thank you, I will try setting this up.
